### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by Vebryn** [EpocDotFr/craft-n-escape#1]
Hello,

It will be nice if item I own list was sort. It will also be nice if a search with an item I own may be partial (ex: Soap will display Sock Mace).

Best regards.

**Comment by EpocDotFr** [comment]
Hi!

> It will be nice if item I own list was sort

This enhancement is already in queue 😄

More generally, all items lists will be sorted by item name (but I encounter technical issues, so it will take a bit of time).

> It will also be nice if a search with an item I own may be partial (ex: Soap will display Sock Mace)

Sorry, I didn't understand.

Thank you for your feedback.

**Comment by Vebryn** [comment]
When I'm looking for recipes with Soap,
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img4.hostingpics.net/pics/933008Screenshotfrom20170814214301.png" border="0" alt="Hebergeur d'image" /></a>
I get _Nothing to display_.
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img4.hostingpics.net/pics/666333Screenshotfrom20170814214947.png" border="0" alt="Hebergeur d'image" /></a>
 I will be glad to see all recipes with Soap ingredient like Sock Mace.
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img4.hostingpics.net/pics/765439Screenshotfrom20170814215017.png" border="0" alt="Hebergeur d'image" /></a>

**Comment by EpocDotFr** [comment]
Thanks for the precision, I understand now.

At the beginning Craft N' Escape worked this way, but at some point I asked myself: if I only own a Soap, I shouldn't be able to craft a Sock Mace because I'm missing a Sock. It's pure logic 🙂
I think I'll add an option to change the "What can I craft" behavior as the user wants.

**Comment by EpocDotFr** [comment]
I just updated Craft N' Escape with a new option allowing partial crafting recipe match when using the _What can I craft?_ feature 😄 

![image](https://user-images.githubusercontent.com/2053431/29332637-00c94f66-8201-11e7-98ca-e40e64534c50.png)

I'll close this issue but create a new one for the items sorting thing (issue #2).

Thanks for your feedback!

**Comment by Vebryn** [comment]
Great! It works like a charm!
